apiVersion: apps/v1
kind: Deployment
metadata:
  name: similarity-service-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: similarity-service-application
  template:
    metadata:
      labels:
        app: similarity-service-application
    spec:
      containers:
      - name: similarity-service-application
        image: arvindveerelli/similarity-service-application:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        - containerPort: 8501
        resources:
          limits:
            memory: "4Gi"
            cpu: "4"
          requests:
            memory: "4Gi"
            cpu: "4"
