apiVersion: v1
kind: Service
metadata:
  name: similarity-service-application
spec:
  selector:
    app: fsimilarity-service-application
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 32000
  type: NodePort